#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom assertthat assert_that
#' @importFrom clusterProfiler GSEA
#' @importFrom DESeq2 counts
#' @importFrom DESeq2 DESeq
#' @importFrom DESeq2 DESeqDataSetFromMatrix
#' @importFrom DESeq2 results
#' @importFrom dplyr across
#' @importFrom dplyr add_row
#' @importFrom dplyr all_of
#' @importFrom dplyr anti_join
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr c_across
#' @importFrom dplyr case_when
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr recode
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr semi_join
#' @importFrom dplyr slice_max
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom edgeR calcNormFactors
#' @importFrom edgeR cpm
#' @importFrom edgeR DGEList
#' @importFrom forcats fct_drop
#' @importFrom fuzzyjoin fuzzy_left_join
#' @importFrom gage gage
#' @importFrom gage sigGeneSet
#' @importFrom grDevices colorRampPalette
#' @importFrom here here
#' @importFrom limma contrasts.fit
#' @importFrom limma eBayes
#' @importFrom limma lmFit
#' @importFrom limma makeContrasts
#' @importFrom limma topTable
#' @importFrom limma voom
#' @importFrom magrittr %>%
#' @importFrom MASS rlm
#' @importFrom methods getClass
#' @importFrom methods new
#' @importFrom msigdbr msigdbr
#' @importFrom purrr imap_dfr
#' @importFrom purrr map2
#' @importFrom purrr map2_dfr
#' @importFrom purrr pmap_dfr
#' @importFrom purrr reduce
#' @importFrom RColorBrewer brewer.pal
#' @importFrom RColorBrewer brewer.pal.info
#' @importFrom readr col_character
#' @importFrom readr col_double
#' @importFrom readr read_tsv
#' @importFrom readxl read_xlsx
#' @importFrom reticulate py_install
#' @importFrom reticulate use_virtualenv
#' @importFrom reticulate virtualenv_create
#' @importFrom shiny runApp
#' @importFrom stats as.formula
#' @importFrom stats mad
#' @importFrom stats median
#' @importFrom stats model.matrix
#' @importFrom stats na.omit
#' @importFrom stats prcomp
#' @importFrom stats setNames
#' @importFrom stats terms
#' @importFrom stats var
#' @importFrom stringr fixed
#' @importFrom stringr regex
#' @importFrom stringr str_detect
#' @importFrom stringr str_starts
#' @importFrom tibble column_to_rownames
#' @importFrom tibble deframe
#' @importFrom tibble enframe
#' @importFrom tibble remove_rownames
#' @importFrom tibble rownames_to_column
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr separate
#' @importFrom utils sessionInfo
#' @importFrom utils write.csv
#' @importFrom viridis viridis
#' @importFrom wesanderson wes_palette
#' @importFrom wesanderson wes_palettes
## usethis namespace: end
NULL
